### ISSUE TITLE
Led Blink1

### ISSUE THREAD

**Issue by brianrachel94** [ffleurey/ThingMLArduinoDemo#2]
Hey for LED Blink2 code when I run in Nodejs I am getting "pinMode not defined" error. How can I overcome this?

Error:

ReferenceError: pinMode is not defined

**Comment by ffleurey** [comment]
Hello, this repo is an Arduino demo. The code is not written to compile for NodeJS.

**Comment by brianrachel94** [comment]
Will it run in RaspberryPI? how can I run the code in RaspberryPI if so?

**Comment by ffleurey** [comment]
Since it is for Arduino, it will not run on a Raspberry Pi. See the reply I gave you on the ThingML repo for getting something working on a Raspberry Pi.
